# Generated by Django 4.2.1 on 2023-08-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
                ('device_number', models.IntegerField()),
                ('handle_on', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('handle_date', models.DateField()),
                ('return_on', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
