# Generated by Django 4.2.1 on 2023-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0003_employee_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='return_date',
            field=models.CharField(max_length=100),
        ),
    ]
