# Generated by Django 4.2.1 on 2023-08-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0005_employeeadd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeadd',
            options={'verbose_name': 'EmployeeAdd', 'verbose_name_plural': 'EmployeeAdd'},
        ),
        migrations.AlterField(
            model_name='device',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_details', to='apptrack.employeeadd'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
