# Generated by Django 4.2.1 on 2023-08-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0007_alter_employeeadd_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeadd',
            name='return_date',
        ),
    ]
