# Generated by Django 4.2.1 on 2023-08-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0009_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='handed_out',
            new_name='given',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='handed_date',
            new_name='given_date',
        ),
    ]
